/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BeatChartEntry {
  'id' : Id,
  'bpm' : bigint,
  'title' : string,
  'rank' : bigint,
  'audioLink' : string,
  'isActive' : boolean,
  'genre' : string,
  'producer' : string,
}
export type Id = bigint;
export interface ProducerTip {
  'id' : Id,
  'isPublished' : boolean,
  'producerImageUrl' : string,
  'producerName' : string,
  'tipTitle' : string,
  'tipBody' : string,
}
export interface RegionEntry {
  'id' : Id,
  'region' : string,
  'country' : string,
  'description' : string,
  'isActive' : boolean,
  'imageUrl' : string,
  'artistName' : string,
  'subregion' : string,
}
export interface Review {
  'id' : Id,
  'isPublished' : boolean,
  'songTitle' : string,
  'reviewerName' : string,
  'reviewedAt' : Time,
  'genre' : string,
  'rating' : bigint,
  'artistName' : string,
  'commentary' : string,
}
export interface RundownStory {
  'id' : Id,
  'title' : string,
  'contentBody' : string,
  'isPublished' : boolean,
  'publishedAt' : Time,
  'author' : string,
  'summary' : string,
  'imageUrl' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface SocialLink { 'url' : string, 'platform' : string }
export interface SongSubmission {
  'id' : Id,
  'status' : string,
  'paymentStatus' : string,
  'songLink' : string,
  'songTitle' : string,
  'submittedAt' : Time,
  'genre' : string,
  'contactEmail' : string,
  'artistName' : string,
  'contactPhone' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface Subscriber {
  'id' : Id,
  'subscribedAt' : Time,
  'email' : string,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WatchListEntry {
  'id' : Id,
  'bio' : string,
  'socialLinks' : Array<SocialLink>,
  'isActive' : boolean,
  'updatedAt' : Time,
  'imageUrl' : string,
  'artistName' : string,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBeatChartEntry' : ActorMethod<[BeatChartEntry], Id>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createProducerTip' : ActorMethod<[ProducerTip], Id>,
  'createRegionEntry' : ActorMethod<[RegionEntry], Id>,
  'createReview' : ActorMethod<[Review], Id>,
  'createRundownStory' : ActorMethod<[RundownStory], Id>,
  'createSongSubmission' : ActorMethod<[SongSubmission], Id>,
  'createSubscriber' : ActorMethod<[string], Id>,
  'createWatchListEntry' : ActorMethod<[WatchListEntry], Id>,
  'deleteBeatChartEntry' : ActorMethod<[Id], undefined>,
  'deleteProducerTip' : ActorMethod<[Id], undefined>,
  'deleteRegionEntry' : ActorMethod<[Id], undefined>,
  'deleteReview' : ActorMethod<[Id], undefined>,
  'deleteRundownStory' : ActorMethod<[Id], undefined>,
  'deleteSongSubmission' : ActorMethod<[Id], undefined>,
  'deleteSubscriber' : ActorMethod<[Id], undefined>,
  'getActiveWatchList' : ActorMethod<[], WatchListEntry>,
  'getAllActiveBeatChartEntries' : ActorMethod<[], Array<BeatChartEntry>>,
  'getAllActiveRegionEntries' : ActorMethod<[], Array<RegionEntry>>,
  'getAllPublishedProducerTips' : ActorMethod<[], Array<ProducerTip>>,
  'getAllPublishedReviews' : ActorMethod<[], Array<Review>>,
  'getAllRundownStories' : ActorMethod<[], Array<RundownStory>>,
  'getAllSongSubmissions' : ActorMethod<[], Array<SongSubmission>>,
  'getAllSubscribers' : ActorMethod<[], Array<Subscriber>>,
  'getAllWatchListEntries' : ActorMethod<[], Array<WatchListEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPublishedRundownStories' : ActorMethod<[], Array<RundownStory>>,
  'getRundownStory' : ActorMethod<[Id], RundownStory>,
  'getSongSubmission' : ActorMethod<[Id], SongSubmission>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setActiveWatchList' : ActorMethod<[Id], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBeatChartEntry' : ActorMethod<[Id, BeatChartEntry], undefined>,
  'updateProducerTip' : ActorMethod<[Id, ProducerTip], undefined>,
  'updateRegionEntry' : ActorMethod<[Id, RegionEntry], undefined>,
  'updateReview' : ActorMethod<[Id, Review], undefined>,
  'updateRundownStory' : ActorMethod<[Id, RundownStory], undefined>,
  'updateSubmissionPaymentStatus' : ActorMethod<[Id, string], undefined>,
  'updateSubmissionStatus' : ActorMethod<[Id, string], undefined>,
  'updateWatchListEntry' : ActorMethod<[Id, WatchListEntry], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];