/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Id = IDL.Nat;
export const BeatChartEntry = IDL.Record({
  'id' : Id,
  'bpm' : IDL.Nat,
  'title' : IDL.Text,
  'rank' : IDL.Nat,
  'audioLink' : IDL.Text,
  'isActive' : IDL.Bool,
  'genre' : IDL.Text,
  'producer' : IDL.Text,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const ProducerTip = IDL.Record({
  'id' : Id,
  'isPublished' : IDL.Bool,
  'producerImageUrl' : IDL.Text,
  'producerName' : IDL.Text,
  'tipTitle' : IDL.Text,
  'tipBody' : IDL.Text,
});
export const RegionEntry = IDL.Record({
  'id' : Id,
  'region' : IDL.Text,
  'country' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'artistName' : IDL.Text,
  'subregion' : IDL.Text,
});
export const Time = IDL.Int;
export const Review = IDL.Record({
  'id' : Id,
  'isPublished' : IDL.Bool,
  'songTitle' : IDL.Text,
  'reviewerName' : IDL.Text,
  'reviewedAt' : Time,
  'genre' : IDL.Text,
  'rating' : IDL.Nat,
  'artistName' : IDL.Text,
  'commentary' : IDL.Text,
});
export const RundownStory = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'contentBody' : IDL.Text,
  'isPublished' : IDL.Bool,
  'publishedAt' : Time,
  'author' : IDL.Text,
  'summary' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const SongSubmission = IDL.Record({
  'id' : Id,
  'status' : IDL.Text,
  'paymentStatus' : IDL.Text,
  'songLink' : IDL.Text,
  'songTitle' : IDL.Text,
  'submittedAt' : Time,
  'genre' : IDL.Text,
  'contactEmail' : IDL.Text,
  'artistName' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const SocialLink = IDL.Record({
  'url' : IDL.Text,
  'platform' : IDL.Text,
});
export const WatchListEntry = IDL.Record({
  'id' : Id,
  'bio' : IDL.Text,
  'socialLinks' : IDL.Vec(SocialLink),
  'isActive' : IDL.Bool,
  'updatedAt' : Time,
  'imageUrl' : IDL.Text,
  'artistName' : IDL.Text,
});
export const Subscriber = IDL.Record({
  'id' : Id,
  'subscribedAt' : Time,
  'email' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBeatChartEntry' : IDL.Func([BeatChartEntry], [Id], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createProducerTip' : IDL.Func([ProducerTip], [Id], []),
  'createRegionEntry' : IDL.Func([RegionEntry], [Id], []),
  'createReview' : IDL.Func([Review], [Id], []),
  'createRundownStory' : IDL.Func([RundownStory], [Id], []),
  'createSongSubmission' : IDL.Func([SongSubmission], [Id], []),
  'createSubscriber' : IDL.Func([IDL.Text], [Id], []),
  'createWatchListEntry' : IDL.Func([WatchListEntry], [Id], []),
  'deleteBeatChartEntry' : IDL.Func([Id], [], []),
  'deleteProducerTip' : IDL.Func([Id], [], []),
  'deleteRegionEntry' : IDL.Func([Id], [], []),
  'deleteReview' : IDL.Func([Id], [], []),
  'deleteRundownStory' : IDL.Func([Id], [], []),
  'deleteSongSubmission' : IDL.Func([Id], [], []),
  'deleteSubscriber' : IDL.Func([Id], [], []),
  'getActiveWatchList' : IDL.Func([], [WatchListEntry], ['query']),
  'getAllActiveBeatChartEntries' : IDL.Func(
      [],
      [IDL.Vec(BeatChartEntry)],
      ['query'],
    ),
  'getAllActiveRegionEntries' : IDL.Func([], [IDL.Vec(RegionEntry)], ['query']),
  'getAllPublishedProducerTips' : IDL.Func(
      [],
      [IDL.Vec(ProducerTip)],
      ['query'],
    ),
  'getAllPublishedReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getAllRundownStories' : IDL.Func([], [IDL.Vec(RundownStory)], ['query']),
  'getAllSongSubmissions' : IDL.Func([], [IDL.Vec(SongSubmission)], []),
  'getAllSubscribers' : IDL.Func([], [IDL.Vec(Subscriber)], []),
  'getAllWatchListEntries' : IDL.Func([], [IDL.Vec(WatchListEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPublishedRundownStories' : IDL.Func(
      [],
      [IDL.Vec(RundownStory)],
      ['query'],
    ),
  'getRundownStory' : IDL.Func([Id], [RundownStory], ['query']),
  'getSongSubmission' : IDL.Func([Id], [SongSubmission], []),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setActiveWatchList' : IDL.Func([Id], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateBeatChartEntry' : IDL.Func([Id, BeatChartEntry], [], []),
  'updateProducerTip' : IDL.Func([Id, ProducerTip], [], []),
  'updateRegionEntry' : IDL.Func([Id, RegionEntry], [], []),
  'updateReview' : IDL.Func([Id, Review], [], []),
  'updateRundownStory' : IDL.Func([Id, RundownStory], [], []),
  'updateSubmissionPaymentStatus' : IDL.Func([Id, IDL.Text], [], []),
  'updateSubmissionStatus' : IDL.Func([Id, IDL.Text], [], []),
  'updateWatchListEntry' : IDL.Func([Id, WatchListEntry], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Id = IDL.Nat;
  const BeatChartEntry = IDL.Record({
    'id' : Id,
    'bpm' : IDL.Nat,
    'title' : IDL.Text,
    'rank' : IDL.Nat,
    'audioLink' : IDL.Text,
    'isActive' : IDL.Bool,
    'genre' : IDL.Text,
    'producer' : IDL.Text,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const ProducerTip = IDL.Record({
    'id' : Id,
    'isPublished' : IDL.Bool,
    'producerImageUrl' : IDL.Text,
    'producerName' : IDL.Text,
    'tipTitle' : IDL.Text,
    'tipBody' : IDL.Text,
  });
  const RegionEntry = IDL.Record({
    'id' : Id,
    'region' : IDL.Text,
    'country' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'artistName' : IDL.Text,
    'subregion' : IDL.Text,
  });
  const Time = IDL.Int;
  const Review = IDL.Record({
    'id' : Id,
    'isPublished' : IDL.Bool,
    'songTitle' : IDL.Text,
    'reviewerName' : IDL.Text,
    'reviewedAt' : Time,
    'genre' : IDL.Text,
    'rating' : IDL.Nat,
    'artistName' : IDL.Text,
    'commentary' : IDL.Text,
  });
  const RundownStory = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'contentBody' : IDL.Text,
    'isPublished' : IDL.Bool,
    'publishedAt' : Time,
    'author' : IDL.Text,
    'summary' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const SongSubmission = IDL.Record({
    'id' : Id,
    'status' : IDL.Text,
    'paymentStatus' : IDL.Text,
    'songLink' : IDL.Text,
    'songTitle' : IDL.Text,
    'submittedAt' : Time,
    'genre' : IDL.Text,
    'contactEmail' : IDL.Text,
    'artistName' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const SocialLink = IDL.Record({ 'url' : IDL.Text, 'platform' : IDL.Text });
  const WatchListEntry = IDL.Record({
    'id' : Id,
    'bio' : IDL.Text,
    'socialLinks' : IDL.Vec(SocialLink),
    'isActive' : IDL.Bool,
    'updatedAt' : Time,
    'imageUrl' : IDL.Text,
    'artistName' : IDL.Text,
  });
  const Subscriber = IDL.Record({
    'id' : Id,
    'subscribedAt' : Time,
    'email' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBeatChartEntry' : IDL.Func([BeatChartEntry], [Id], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createProducerTip' : IDL.Func([ProducerTip], [Id], []),
    'createRegionEntry' : IDL.Func([RegionEntry], [Id], []),
    'createReview' : IDL.Func([Review], [Id], []),
    'createRundownStory' : IDL.Func([RundownStory], [Id], []),
    'createSongSubmission' : IDL.Func([SongSubmission], [Id], []),
    'createSubscriber' : IDL.Func([IDL.Text], [Id], []),
    'createWatchListEntry' : IDL.Func([WatchListEntry], [Id], []),
    'deleteBeatChartEntry' : IDL.Func([Id], [], []),
    'deleteProducerTip' : IDL.Func([Id], [], []),
    'deleteRegionEntry' : IDL.Func([Id], [], []),
    'deleteReview' : IDL.Func([Id], [], []),
    'deleteRundownStory' : IDL.Func([Id], [], []),
    'deleteSongSubmission' : IDL.Func([Id], [], []),
    'deleteSubscriber' : IDL.Func([Id], [], []),
    'getActiveWatchList' : IDL.Func([], [WatchListEntry], ['query']),
    'getAllActiveBeatChartEntries' : IDL.Func(
        [],
        [IDL.Vec(BeatChartEntry)],
        ['query'],
      ),
    'getAllActiveRegionEntries' : IDL.Func(
        [],
        [IDL.Vec(RegionEntry)],
        ['query'],
      ),
    'getAllPublishedProducerTips' : IDL.Func(
        [],
        [IDL.Vec(ProducerTip)],
        ['query'],
      ),
    'getAllPublishedReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getAllRundownStories' : IDL.Func([], [IDL.Vec(RundownStory)], ['query']),
    'getAllSongSubmissions' : IDL.Func([], [IDL.Vec(SongSubmission)], []),
    'getAllSubscribers' : IDL.Func([], [IDL.Vec(Subscriber)], []),
    'getAllWatchListEntries' : IDL.Func(
        [],
        [IDL.Vec(WatchListEntry)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPublishedRundownStories' : IDL.Func(
        [],
        [IDL.Vec(RundownStory)],
        ['query'],
      ),
    'getRundownStory' : IDL.Func([Id], [RundownStory], ['query']),
    'getSongSubmission' : IDL.Func([Id], [SongSubmission], []),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setActiveWatchList' : IDL.Func([Id], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateBeatChartEntry' : IDL.Func([Id, BeatChartEntry], [], []),
    'updateProducerTip' : IDL.Func([Id, ProducerTip], [], []),
    'updateRegionEntry' : IDL.Func([Id, RegionEntry], [], []),
    'updateReview' : IDL.Func([Id, Review], [], []),
    'updateRundownStory' : IDL.Func([Id, RundownStory], [], []),
    'updateSubmissionPaymentStatus' : IDL.Func([Id, IDL.Text], [], []),
    'updateSubmissionStatus' : IDL.Func([Id, IDL.Text], [], []),
    'updateWatchListEntry' : IDL.Func([Id, WatchListEntry], [], []),
  });
};

export const init = ({ IDL }) => { return []; };