/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RegionEntry {
    id: Id;
    region: string;
    country: string;
    description: string;
    isActive: boolean;
    imageUrl: string;
    artistName: string;
    subregion: string;
}
export interface WatchListEntry {
    id: Id;
    bio: string;
    socialLinks: Array<SocialLink>;
    isActive: boolean;
    updatedAt: Time;
    imageUrl: string;
    artistName: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface RundownStory {
    id: Id;
    title: string;
    contentBody: string;
    isPublished: boolean;
    publishedAt: Time;
    author: string;
    summary: string;
    imageUrl: string;
}
export interface SocialLink {
    url: string;
    platform: string;
}
export interface BeatChartEntry {
    id: Id;
    bpm: bigint;
    title: string;
    rank: bigint;
    audioLink: string;
    isActive: boolean;
    genre: string;
    producer: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type Id = bigint;
export interface Subscriber {
    id: Id;
    subscribedAt: Time;
    email: string;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface ProducerTip {
    id: Id;
    isPublished: boolean;
    producerImageUrl: string;
    producerName: string;
    tipTitle: string;
    tipBody: string;
}
export interface SongSubmission {
    id: Id;
    status: string;
    paymentStatus: string;
    songLink: string;
    songTitle: string;
    submittedAt: Time;
    genre: string;
    contactEmail: string;
    artistName: string;
    contactPhone: string;
}
export interface UserProfile {
    name: string;
}
export interface Review {
    id: Id;
    isPublished: boolean;
    songTitle: string;
    reviewerName: string;
    reviewedAt: Time;
    genre: string;
    rating: bigint;
    artistName: string;
    commentary: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBeatChartEntry(entry: BeatChartEntry): Promise<Id>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createProducerTip(tip: ProducerTip): Promise<Id>;
    createRegionEntry(entry: RegionEntry): Promise<Id>;
    createReview(review: Review): Promise<Id>;
    createRundownStory(story: RundownStory): Promise<Id>;
    createSongSubmission(submission: SongSubmission): Promise<Id>;
    createSubscriber(email: string): Promise<Id>;
    createWatchListEntry(entry: WatchListEntry): Promise<Id>;
    deleteBeatChartEntry(id: Id): Promise<void>;
    deleteProducerTip(id: Id): Promise<void>;
    deleteRegionEntry(id: Id): Promise<void>;
    deleteReview(id: Id): Promise<void>;
    deleteRundownStory(id: Id): Promise<void>;
    deleteSongSubmission(id: Id): Promise<void>;
    deleteSubscriber(id: Id): Promise<void>;
    getActiveWatchList(): Promise<WatchListEntry>;
    getAllActiveBeatChartEntries(): Promise<Array<BeatChartEntry>>;
    getAllActiveRegionEntries(): Promise<Array<RegionEntry>>;
    getAllPublishedProducerTips(): Promise<Array<ProducerTip>>;
    getAllPublishedReviews(): Promise<Array<Review>>;
    getAllRundownStories(): Promise<Array<RundownStory>>;
    getAllSongSubmissions(): Promise<Array<SongSubmission>>;
    getAllSubscribers(): Promise<Array<Subscriber>>;
    getAllWatchListEntries(): Promise<Array<WatchListEntry>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getPublishedRundownStories(): Promise<Array<RundownStory>>;
    getRundownStory(id: Id): Promise<RundownStory>;
    getSongSubmission(id: Id): Promise<SongSubmission>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setActiveWatchList(id: Id): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateBeatChartEntry(id: Id, entry: BeatChartEntry): Promise<void>;
    updateProducerTip(id: Id, tip: ProducerTip): Promise<void>;
    updateRegionEntry(id: Id, entry: RegionEntry): Promise<void>;
    updateReview(id: Id, review: Review): Promise<void>;
    updateRundownStory(id: Id, story: RundownStory): Promise<void>;
    updateSubmissionPaymentStatus(id: Id, paymentStatus: string): Promise<void>;
    updateSubmissionStatus(id: Id, status: string): Promise<void>;
    updateWatchListEntry(id: Id, entry: WatchListEntry): Promise<void>;
}
import type { StripeSessionStatus as _StripeSessionStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBeatChartEntry(arg0: BeatChartEntry): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.createBeatChartEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBeatChartEntry(arg0);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createProducerTip(arg0: ProducerTip): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.createProducerTip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProducerTip(arg0);
            return result;
        }
    }
    async createRegionEntry(arg0: RegionEntry): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.createRegionEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRegionEntry(arg0);
            return result;
        }
    }
    async createReview(arg0: Review): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.createReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReview(arg0);
            return result;
        }
    }
    async createRundownStory(arg0: RundownStory): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.createRundownStory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRundownStory(arg0);
            return result;
        }
    }
    async createSongSubmission(arg0: SongSubmission): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.createSongSubmission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSongSubmission(arg0);
            return result;
        }
    }
    async createSubscriber(arg0: string): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.createSubscriber(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSubscriber(arg0);
            return result;
        }
    }
    async createWatchListEntry(arg0: WatchListEntry): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.createWatchListEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWatchListEntry(arg0);
            return result;
        }
    }
    async deleteBeatChartEntry(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBeatChartEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBeatChartEntry(arg0);
            return result;
        }
    }
    async deleteProducerTip(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProducerTip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProducerTip(arg0);
            return result;
        }
    }
    async deleteRegionEntry(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRegionEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRegionEntry(arg0);
            return result;
        }
    }
    async deleteReview(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReview(arg0);
            return result;
        }
    }
    async deleteRundownStory(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRundownStory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRundownStory(arg0);
            return result;
        }
    }
    async deleteSongSubmission(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSongSubmission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSongSubmission(arg0);
            return result;
        }
    }
    async deleteSubscriber(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSubscriber(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSubscriber(arg0);
            return result;
        }
    }
    async getActiveWatchList(): Promise<WatchListEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveWatchList();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveWatchList();
            return result;
        }
    }
    async getAllActiveBeatChartEntries(): Promise<Array<BeatChartEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActiveBeatChartEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActiveBeatChartEntries();
            return result;
        }
    }
    async getAllActiveRegionEntries(): Promise<Array<RegionEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActiveRegionEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActiveRegionEntries();
            return result;
        }
    }
    async getAllPublishedProducerTips(): Promise<Array<ProducerTip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublishedProducerTips();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublishedProducerTips();
            return result;
        }
    }
    async getAllPublishedReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublishedReviews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublishedReviews();
            return result;
        }
    }
    async getAllRundownStories(): Promise<Array<RundownStory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRundownStories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRundownStories();
            return result;
        }
    }
    async getAllSongSubmissions(): Promise<Array<SongSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSongSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSongSubmissions();
            return result;
        }
    }
    async getAllSubscribers(): Promise<Array<Subscriber>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubscribers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubscribers();
            return result;
        }
    }
    async getAllWatchListEntries(): Promise<Array<WatchListEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWatchListEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWatchListEntries();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublishedRundownStories(): Promise<Array<RundownStory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedRundownStories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedRundownStories();
            return result;
        }
    }
    async getRundownStory(arg0: Id): Promise<RundownStory> {
        if (this.processError) {
            try {
                const result = await this.actor.getRundownStory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRundownStory(arg0);
            return result;
        }
    }
    async getSongSubmission(arg0: Id): Promise<SongSubmission> {
        if (this.processError) {
            try {
                const result = await this.actor.getSongSubmission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSongSubmission(arg0);
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setActiveWatchList(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setActiveWatchList(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setActiveWatchList(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateBeatChartEntry(arg0: Id, arg1: BeatChartEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBeatChartEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBeatChartEntry(arg0, arg1);
            return result;
        }
    }
    async updateProducerTip(arg0: Id, arg1: ProducerTip): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProducerTip(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProducerTip(arg0, arg1);
            return result;
        }
    }
    async updateRegionEntry(arg0: Id, arg1: RegionEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRegionEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRegionEntry(arg0, arg1);
            return result;
        }
    }
    async updateReview(arg0: Id, arg1: Review): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReview(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReview(arg0, arg1);
            return result;
        }
    }
    async updateRundownStory(arg0: Id, arg1: RundownStory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRundownStory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRundownStory(arg0, arg1);
            return result;
        }
    }
    async updateSubmissionPaymentStatus(arg0: Id, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubmissionPaymentStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubmissionPaymentStatus(arg0, arg1);
            return result;
        }
    }
    async updateSubmissionStatus(arg0: Id, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubmissionStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubmissionStatus(arg0, arg1);
            return result;
        }
    }
    async updateWatchListEntry(arg0: Id, arg1: WatchListEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWatchListEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWatchListEntry(arg0, arg1);
            return result;
        }
    }
}
function from_candid_StripeSessionStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n8(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
